export { default as Chart } from './logo.png';
export { default as Google } from './googlelogo.png'
export { default as Amazon } from './amazonlogo.png'
export { default as Group }  from './Group 1171274761.png'
export { default as FedEx } from './fedexlogo.png'
export { default as Image1 } from './image(1).png'
export { default as Image2 } from './image(2).png'
export { default as Image3 } from './image(3).png'
export { default as Image4 } from './image(4).png'
export { default as Image5 } from './image(5).png'
export { default as Microsoft } from './microsoftlogo.png'
export { default as Ola } from './olalogo.png'
export { default as Oyo } from './oyologo.png'
export { default as Walmart } from './walmart-logo.png'
export { default as Airbnb } from './airbnb.png'
export { default as Arrow } from './arrow.png'
export { default as Content } from '../img/image2.png'
export { default as Vector } from './Vector.png'